services:
  postgres-db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - appointments-network

  appointments-api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      - DATABASE_URL
      - MINIO_ENDPOINT
    networks:
      - appointments-network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9090"
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - ./minio-data:/data
      - ./minio-init:/docker-entrypoint-init.d
    networks:
      - appointments-network

networks:
  appointments-network:
    driver: bridge
